package org.example.Backend;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

class testNew {


    @Test
    public void getTestCombineFXML() {
        String[] passKeeper = {"a", "b", "c", "", "f", "g"};
        String[] newPane = {"d", "e"};
        String[] expected = {"a", "b", "c", "d", "e", "", "f", "g"};

        New.passKeeper = passKeeper;
        New.newPane = newPane;
        New.newLine = 3;


        New.combineFXML();

        assertArrayEquals(expected, New.newFXML);

    }

    @Test
    public void getTestCombineFXMLComplex() {
        New.newLine = 18;
        String[] newPane = {"<Pane layoutX=\"84.0\" layoutY=\" " + "heightIncrease" + "\" prefHeight=\"97.0\" prefWidth=\"472.0\">",
                "                                 <children>",
                "                                    <Rectangle arcHeight=\"15.0\" arcWidth=\"15.0\" fill=\"#202225\" height=\"96.0\" opacity=\"0.76\" stroke=\"#e1e1e1\" strokeLineCap=\"ROUND\" strokeWidth=\"0.0\" width=\"471.0\" />",
                "                                    <Label layoutX=\"14.0\" layoutY=\"9.0\" text=\"" + "this.user" + "\" textFill=\"#bcbcbc\">\n" +
                        "                                       <font>",
                "                                          <Font name=\"Calibri Bold\" size=\"20.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"59.0\" layoutY=\"37.0\" text=\"Account:\" textFill=\"#b5b5b5\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"50.0\" layoutY=\"63.0\" text=\"Password:\" textFill=\"#bfbfbf\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"132.0\" layoutY=\"66.0\" text=\" " + "this.password" + "\" textFill=\"#b9b9b9\">,",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />\n",
                "                                       </font>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"TEXT\" />",
                "                                       </cursor>",
                "                                    </Label>",
                "                                    <Label layoutX=\"132.0\" layoutY=\"38.0\" text=\"" + "this.user" + "\" textFill=\"#b2b2b2\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"TEXT\" />",
                "                                       </cursor>",
                "                                    </Label>",
                "                                    <Button layoutX=\"343.0\" layoutY=\"62.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Reveal\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                    <Button layoutX=\"405.0\" layoutY=\"62.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Change\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                    <Button layoutX=\"433.0\" layoutY=\"8.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"\uD83D\uDDD1\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                 </children>",
                "                              </Pane>"
                };

        String[] passKeeper = {
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
                "<?import javafx.scene.Cursor?>",
                "<?import javafx.scene.control.Button?>",
                "<?import javafx.scene.control.Label?>",
                "<?import javafx.scene.control.Slider?>",
                "<?import javafx.scene.control.SplitPane?>",
                "<?import javafx.scene.control.TextField?>",
                "<?import javafx.scene.effect.DropShadow?>",
                "<?import javafx.scene.layout.AnchorPane?>",
                "<?import javafx.scene.layout.Pane?>",
                "<?import javafx.scene.shape.Rectangle?>",
                "<?import javafx.scene.text.Font?>",
                "<Pane maxHeight=\"-Infinity\" maxWidth=\"-Infinity\" minHeight=\"-Infinity\" minWidth=\"-Infinity\" prefHeight=\"582.0\" prefWidth=\"891.0\" xmlns=\"http://javafx.com/javafx/22\" xmlns:fx=\"http://javafx.com/fxml/1\" fx:controller=\"org.example.Controllers.passKeeperController\">",
                "   <children>",
                "      <Rectangle arcHeight=\"5.0\" arcWidth=\"5.0\" fill=\"#202225\" height=\"105.0\" stroke=\"BLACK\" strokeType=\"INSIDE\" strokeWidth=\"0.0\" width=\"891.0\" />",
                "      <SplitPane layoutX=\"1.0\" layoutY=\"104.0\" prefHeight=\"478.0\" prefWidth=\"891.0\" style=\"-fx-background-color: GREY;\">",
                "        <items>",
                "",
                "         <!-- Add -->",
                "          <AnchorPane minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"476.0\" prefWidth=\"306.0\">",
                "               <children>",
                "                  <Rectangle arcHeight=\"5.0\" arcWidth=\"5.0\" fill=\"#202225\" height=\"478.0\" stroke=\"BLACK\" strokeType=\"INSIDE\" strokeWidth=\"0.0\" width=\"227.0\" />",
                "                  <TextField layoutX=\"20.0\" layoutY=\"69.0\" prefHeight=\"26.0\" prefWidth=\"176.0\" style=\"-fx-background-color: grey;\">",
                "                     <cursor>",
                "                        <Cursor fx:constant=\"TEXT\" />",
                "                     </cursor>",
                "                  </TextField>",
                "                  <Button layoutX=\"14.0\" layoutY=\"437.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"?\">",
                "                     <cursor>",
                "                        <Cursor fx:constant=\"HAND\" />",
                "                     </cursor>",
                "                  </Button>",
                "                  <Label layoutX=\"81.0\" layoutY=\"43.0\" text=\"Search\" textFill=\"#b2b1b1\">",
                "                     <font>",
                "                        <Font name=\"Cambria\" size=\"16.0\" />",
                "                     </font>",
                "                  </Label>",
                "                  <Label layoutX=\"48.0\" layoutY=\"160.0\" text=\"Add new password\" textFill=\"#b2b1b1\">",
                "                     <font>",
                "                        <Font name=\"Cambria\" size=\"16.0\" />",
                "                     </font>",
                "                  </Label>",
                "                  <AnchorPane layoutX=\"227.0\" minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"360.0\" prefWidth=\"669.0\">",
                "                     <children>",
                "                        <Pane prefHeight=\"476.0\" prefWidth=\"656.0\">",
                "                           <children>",
                "                              <Rectangle arcHeight=\"5.0\" arcWidth=\"5.0\" fill=\"#40444b\" height=\"478.0\" layoutY=\"-1.0\" stroke=\"BLACK\" strokeType=\"INSIDE\" strokeWidth=\"0.0\" width=\"662.0\" />",
                "                              <Slider layoutX=\"612.0\" layoutY=\"17.0\" opacity=\"0.25\" orientation=\"VERTICAL\" prefHeight=\"441.0\" prefWidth=\"14.0\" />",
                "                              <Pane layoutX=\"84.0\" layoutY=\"44.0\" prefHeight=\"97.0\" prefWidth=\"472.0\">",
                "                                 <children>",
                "                                    <Rectangle arcHeight=\"15.0\" arcWidth=\"15.0\" fill=\"#202225\" height=\"96.0\" opacity=\"0.76\" stroke=\"#e1e1e1\" strokeLineCap=\"ROUND\" strokeWidth=\"0.0\" width=\"471.0\" />",
                "                                    <Label layoutX=\"14.0\" layoutY=\"9.0\" text=\"Gmail\" textFill=\"#bcbcbc\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri Bold\" size=\"20.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"59.0\" layoutY=\"37.0\" text=\"Account:\" textFill=\"#b5b5b5\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"50.0\" layoutY=\"63.0\" text=\"Password:\" textFill=\"#bfbfbf\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"132.0\" layoutY=\"66.0\" text=\"**********\" textFill=\"#b9b9b9\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"TEXT\" />",
                "                                       </cursor>",
                "                                    </Label>",
                "                                    <Label layoutX=\"132.0\" layoutY=\"38.0\" text=\"Example@gmail.com\" textFill=\"#b2b2b2\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"TEXT\" />",
                "                                       </cursor>",
                "                                    </Label>",
                "                                    <Button layoutX=\"343.0\" layoutY=\"62.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Reveal\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                    <Button layoutX=\"405.0\" layoutY=\"62.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Change\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                    <Button layoutX=\"433.0\" layoutY=\"8.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"🗑\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                 </children>",
                "                              </Pane>",
                "                              <Pane layoutX=\"84.0\" layoutY=\"149.0\" prefHeight=\"97.0\" prefWidth=\"472.0\">",
                "                                 <children>",
                "                                    <Rectangle arcHeight=\"15.0\" arcWidth=\"15.0\" fill=\"#202225\" height=\"96.0\" opacity=\"0.76\" stroke=\"#979797\" strokeLineCap=\"ROUND\" strokeWidth=\"0.0\" width=\"471.0\" />",
                "                                    <Label layoutX=\"14.0\" layoutY=\"9.0\" text=\"Facebook\" textFill=\"#b5b5b5\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri Bold\" size=\"20.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"55.0\" layoutY=\"36.0\" text=\"Account:\" textFill=\"#b5b5b5\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"50.0\" layoutY=\"62.0\" text=\"Password:\" textFill=\"#bfbfbf\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"132.0\" layoutY=\"64.0\" text=\"*********\" textFill=\"#b9b9b9\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"TEXT\" />",
                "                                       </cursor>",
                "                                    </Label>",
                "                                    <Label layoutX=\"132.0\" layoutY=\"36.0\" text=\"Example@gmail.com\" textFill=\"#b2b2b2\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"TEXT\" />",
                "                                       </cursor>",
                "                                    </Label>",
                "                                    <Button layoutX=\"343.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Reveal\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                    <Button layoutX=\"405.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Change\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                    <Button layoutX=\"433.0\" layoutY=\"6.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"🗑\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                 </children>",
                "                              </Pane>",
                "                              <Pane layoutX=\"83.0\" layoutY=\"258.0\" prefHeight=\"97.0\" prefWidth=\"472.0\">",
                "                                 <children>",
                "                                    <Rectangle arcHeight=\"15.0\" arcWidth=\"15.0\" fill=\"#202225\" height=\"96.0\" opacity=\"0.76\" stroke=\"#979797\" strokeLineCap=\"ROUND\" strokeWidth=\"0.0\" width=\"471.0\" />",
                "                                    <Label layoutX=\"14.0\" layoutY=\"9.0\" text=\"Twitter\" textFill=\"#b5b5b5\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri Bold\" size=\"20.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"55.0\" layoutY=\"36.0\" text=\"Account:\" textFill=\"#b5b5b5\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"50.0\" layoutY=\"62.0\" text=\"Password:\" textFill=\"#bfbfbf\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"132.0\" layoutY=\"64.0\" text=\"*********\" textFill=\"#b9b9b9\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"TEXT\" />",
                "                                       </cursor>",
                "                                    </Label>",
                "                                    <Label layoutX=\"132.0\" layoutY=\"36.0\" text=\"Example@gmail.com\" textFill=\"#b2b2b2\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"TEXT\" />",
                "                                       </cursor>",
                "                                    </Label>",
                "                                    <Button layoutX=\"343.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Reveal\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                    <Button layoutX=\"405.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Change\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                    <Button layoutX=\"433.0\" layoutY=\"6.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"🗑\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                 </children>",
                "                              </Pane>",
                "                              <Pane layoutX=\"82.0\" layoutY=\"373.0\" prefHeight=\"97.0\" prefWidth=\"472.0\">",
                "                                 <children>",
                "                                    <Rectangle arcHeight=\"15.0\" arcWidth=\"15.0\" fill=\"#202225\" height=\"96.0\" opacity=\"0.76\" stroke=\"#979797\" strokeLineCap=\"ROUND\" strokeWidth=\"0.0\" width=\"471.0\" />",
                "                                    <Label layoutX=\"14.0\" layoutY=\"9.0\" text=\"Instagram\" textFill=\"#b5b5b5\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri Bold\" size=\"20.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"55.0\" layoutY=\"36.0\" text=\"Account:\" textFill=\"#b5b5b5\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"50.0\" layoutY=\"62.0\" text=\"Password:\" textFill=\"#bfbfbf\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"132.0\" layoutY=\"64.0\" text=\"*********\" textFill=\"#b9b9b9\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"TEXT\" />",
                "                                       </cursor>",
                "                                    </Label>",
                "                                    <Label layoutX=\"132.0\" layoutY=\"36.0\" text=\"Example@gmail.com\" textFill=\"#b2b2b2\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"TEXT\" />",
                "                                       </cursor>",
                "                                    </Label>",
                "                                    <Button layoutX=\"343.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Reveal\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                    <Button layoutX=\"405.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Change\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                    <Button layoutX=\"433.0\" layoutY=\"6.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"🗑\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                 </children>",
                "                              </Pane>",
                "                              <Pane layoutX=\"83.0\" layoutY=\"488.0\" prefHeight=\"97.0\" prefWidth=\"472.0\">",
                "                                 <children>",
                "                                    <Rectangle arcHeight=\"15.0\" arcWidth=\"15.0\" fill=\"#202225\" height=\"96.0\" opacity=\"0.76\" stroke=\"#979797\" strokeLineCap=\"ROUND\" strokeWidth=\"0.0\" width=\"471.0\" />",
                "                                    <Label layoutX=\"14.0\" layoutY=\"9.0\" text=\"LinkedIn\" textFill=\"#b5b5b5\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri Bold\" size=\"20.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"55.0\" layoutY=\"36.0\" text=\"Account:\" textFill=\"#b5b5b5\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"50.0\" layoutY=\"62.0\" text=\"Password:\" textFill=\"#bfbfbf\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                    </Label>",
                "                                    <Label layoutX=\"132.0\" layoutY=\"64.0\" text=\"*********\" textFill=\"#b9b9b9\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"TEXT\" />",
                "                                       </cursor>",
                "                                    </Label>",
                "                                    <Label layoutX=\"132.0\" layoutY=\"36.0\" text=\"Example@gmail.com\" textFill=\"#b2b2b2\">",
                "                                       <font>",
                "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                "                                       </font>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"TEXT\" />",
                "                                       </cursor>",
                "                                    </Label>",
                "                                    <Button layoutX=\"343.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Reveal\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                    <Button layoutX=\"405.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Change\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                    <Button layoutX=\"433.0\" layoutY=\"6.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"🗑\">",
                "                                       <effect>",
                "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                "                                       </effect>",
                "                                       <cursor>",
                "                                          <Cursor fx:constant=\"HAND\" />",
                "                                       </cursor>",
                "                                    </Button>",
                "                                 </children>",
                "                              </Pane>",
                "                           </children>",
                "                        </AnchorPane>",
                "                        <AnchorPane minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"180.0\" prefWidth=\"200.0\" />",
                "                     </items>",
                "                  </SplitPane>",
                "                  <HBox.alignment>",
                "                     <Pos fx:constant=\"CENTER_LEFT\" />",
                "                  </HBox.alignment>",
                "               </children>",
                "            </HBox>",
                "         </content>",
                "      </Tab>",
                "   </tabs>",
                "   <effect>",
                "      <DropShadow />",
                "   </effect>",
                "   <focusTraversable>true</focusTraversable>",
                "   <stylesheets>",
                "      <URL value=\"../stylesheet.css\" />",
                "   </stylesheets>",
                "</TabPane>"};

        String[] expected = {
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
                    "<?import javafx.scene.Cursor?>",
                    "<?import javafx.scene.control.Button?>",
                    "<?import javafx.scene.control.Label?>",
                    "<?import javafx.scene.control.Slider?>",
                    "<?import javafx.scene.control.SplitPane?>",
                    "<?import javafx.scene.control.TextField?>",
                    "<?import javafx.scene.effect.DropShadow?>",
                    "<?import javafx.scene.layout.AnchorPane?>",
                    "<?import javafx.scene.layout.Pane?>",
                    "<?import javafx.scene.shape.Rectangle?>",
                    "<?import javafx.scene.text.Font?>",
                    "<Pane maxHeight=\"-Infinity\" maxWidth=\"-Infinity\" minHeight=\"-Infinity\" minWidth=\"-Infinity\" prefHeight=\"582.0\" prefWidth=\"891.0\" xmlns=\"http://javafx.com/javafx/22\" xmlns:fx=\"http://javafx.com/fxml/1\" fx:controller=\"org.example.Controllers.passKeeperController\">",
                    "   <children>",
                    "      <Rectangle arcHeight=\"5.0\" arcWidth=\"5.0\" fill=\"#202225\" height=\"105.0\" stroke=\"BLACK\" strokeType=\"INSIDE\" strokeWidth=\"0.0\" width=\"891.0\" />",
                    "      <SplitPane layoutX=\"1.0\" layoutY=\"104.0\" prefHeight=\"478.0\" prefWidth=\"891.0\" style=\"-fx-background-color: GREY;\">",
                    "        <items>",
                    "",
                    "<Pane layoutX=\"84.0\" layoutY=\" " + "heightIncrease" + "\" prefHeight=\"97.0\" prefWidth=\"472.0\">",
                    "                                 <children>",
                    "                                    <Rectangle arcHeight=\"15.0\" arcWidth=\"15.0\" fill=\"#202225\" height=\"96.0\" opacity=\"0.76\" stroke=\"#e1e1e1\" strokeLineCap=\"ROUND\" strokeWidth=\"0.0\" width=\"471.0\" />",
                    "                                    <Label layoutX=\"14.0\" layoutY=\"9.0\" text=\"" + "this.user" + "\" textFill=\"#bcbcbc\">\n" + "                                       <font>",
                    "                                          <Font name=\"Calibri Bold\" size=\"20.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"59.0\" layoutY=\"37.0\" text=\"Account:\" textFill=\"#b5b5b5\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"50.0\" layoutY=\"63.0\" text=\"Password:\" textFill=\"#bfbfbf\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"132.0\" layoutY=\"66.0\" text=\" " + "this.password" + "\" textFill=\"#b9b9b9\">,",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />\n",
                    "                                       </font>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"TEXT\" />",
                    "                                       </cursor>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"132.0\" layoutY=\"38.0\" text=\"" + "this.user" + "\" textFill=\"#b2b2b2\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"TEXT\" />",
                    "                                       </cursor>",
                    "                                    </Label>",
                    "                                    <Button layoutX=\"343.0\" layoutY=\"62.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Reveal\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                    <Button layoutX=\"405.0\" layoutY=\"62.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Change\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                    <Button layoutX=\"433.0\" layoutY=\"8.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"\uD83D\uDDD1\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                 </children>",
                    "                              </Pane>",

                    "         <!-- Add -->",
                    "          <AnchorPane minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"476.0\" prefWidth=\"306.0\">",
                    "               <children>",
                    "                  <Rectangle arcHeight=\"5.0\" arcWidth=\"5.0\" fill=\"#202225\" height=\"478.0\" stroke=\"BLACK\" strokeType=\"INSIDE\" strokeWidth=\"0.0\" width=\"227.0\" />",
                    "                  <TextField layoutX=\"20.0\" layoutY=\"69.0\" prefHeight=\"26.0\" prefWidth=\"176.0\" style=\"-fx-background-color: grey;\">",
                    "                     <cursor>",
                    "                        <Cursor fx:constant=\"TEXT\" />",
                    "                     </cursor>",
                    "                  </TextField>",
                    "                  <Button layoutX=\"14.0\" layoutY=\"437.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"?\">",
                    "                     <cursor>",
                    "                        <Cursor fx:constant=\"HAND\" />",
                    "                     </cursor>",
                    "                  </Button>",
                    "                  <Label layoutX=\"81.0\" layoutY=\"43.0\" text=\"Search\" textFill=\"#b2b1b1\">",
                    "                     <font>",
                    "                        <Font name=\"Cambria\" size=\"16.0\" />",
                    "                     </font>",
                    "                  </Label>",
                    "                  <Label layoutX=\"48.0\" layoutY=\"160.0\" text=\"Add new password\" textFill=\"#b2b1b1\">",
                    "                     <font>",
                    "                        <Font name=\"Cambria\" size=\"16.0\" />",
                    "                     </font>",
                    "                  </Label>",
                    "                  <AnchorPane layoutX=\"227.0\" minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"360.0\" prefWidth=\"669.0\">",
                    "                     <children>",
                    "                        <Pane prefHeight=\"476.0\" prefWidth=\"656.0\">",
                    "                           <children>",
                    "                              <Rectangle arcHeight=\"5.0\" arcWidth=\"5.0\" fill=\"#40444b\" height=\"478.0\" layoutY=\"-1.0\" stroke=\"BLACK\" strokeType=\"INSIDE\" strokeWidth=\"0.0\" width=\"662.0\" />",
                    "                              <Slider layoutX=\"612.0\" layoutY=\"17.0\" opacity=\"0.25\" orientation=\"VERTICAL\" prefHeight=\"441.0\" prefWidth=\"14.0\" />",
                    "                              <Pane layoutX=\"84.0\" layoutY=\"44.0\" prefHeight=\"97.0\" prefWidth=\"472.0\">",
                    "                                 <children>",
                    "                                    <Rectangle arcHeight=\"15.0\" arcWidth=\"15.0\" fill=\"#202225\" height=\"96.0\" opacity=\"0.76\" stroke=\"#e1e1e1\" strokeLineCap=\"ROUND\" strokeWidth=\"0.0\" width=\"471.0\" />",
                    "                                    <Label layoutX=\"14.0\" layoutY=\"9.0\" text=\"Gmail\" textFill=\"#bcbcbc\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri Bold\" size=\"20.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"59.0\" layoutY=\"37.0\" text=\"Account:\" textFill=\"#b5b5b5\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"50.0\" layoutY=\"63.0\" text=\"Password:\" textFill=\"#bfbfbf\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"132.0\" layoutY=\"66.0\" text=\"**********\" textFill=\"#b9b9b9\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"TEXT\" />",
                    "                                       </cursor>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"132.0\" layoutY=\"38.0\" text=\"Example@gmail.com\" textFill=\"#b2b2b2\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"TEXT\" />",
                    "                                       </cursor>",
                    "                                    </Label>",
                    "                                    <Button layoutX=\"343.0\" layoutY=\"62.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Reveal\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                    <Button layoutX=\"405.0\" layoutY=\"62.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Change\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                    <Button layoutX=\"433.0\" layoutY=\"8.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"🗑\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                 </children>",
                    "                              </Pane>",
                    "                              <Pane layoutX=\"84.0\" layoutY=\"149.0\" prefHeight=\"97.0\" prefWidth=\"472.0\">",
                    "                                 <children>",
                    "                                    <Rectangle arcHeight=\"15.0\" arcWidth=\"15.0\" fill=\"#202225\" height=\"96.0\" opacity=\"0.76\" stroke=\"#979797\" strokeLineCap=\"ROUND\" strokeWidth=\"0.0\" width=\"471.0\" />",
                    "                                    <Label layoutX=\"14.0\" layoutY=\"9.0\" text=\"Facebook\" textFill=\"#b5b5b5\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri Bold\" size=\"20.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"55.0\" layoutY=\"36.0\" text=\"Account:\" textFill=\"#b5b5b5\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"50.0\" layoutY=\"62.0\" text=\"Password:\" textFill=\"#bfbfbf\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"132.0\" layoutY=\"64.0\" text=\"*********\" textFill=\"#b9b9b9\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"TEXT\" />",
                    "                                       </cursor>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"132.0\" layoutY=\"36.0\" text=\"Example@gmail.com\" textFill=\"#b2b2b2\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"TEXT\" />",
                    "                                       </cursor>",
                    "                                    </Label>",
                    "                                    <Button layoutX=\"343.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Reveal\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                    <Button layoutX=\"405.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Change\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                    <Button layoutX=\"433.0\" layoutY=\"6.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"🗑\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                 </children>",
                    "                              </Pane>",
                    "                              <Pane layoutX=\"83.0\" layoutY=\"258.0\" prefHeight=\"97.0\" prefWidth=\"472.0\">",
                    "                                 <children>",
                    "                                    <Rectangle arcHeight=\"15.0\" arcWidth=\"15.0\" fill=\"#202225\" height=\"96.0\" opacity=\"0.76\" stroke=\"#979797\" strokeLineCap=\"ROUND\" strokeWidth=\"0.0\" width=\"471.0\" />",
                    "                                    <Label layoutX=\"14.0\" layoutY=\"9.0\" text=\"Twitter\" textFill=\"#b5b5b5\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri Bold\" size=\"20.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"55.0\" layoutY=\"36.0\" text=\"Account:\" textFill=\"#b5b5b5\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"50.0\" layoutY=\"62.0\" text=\"Password:\" textFill=\"#bfbfbf\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"132.0\" layoutY=\"64.0\" text=\"*********\" textFill=\"#b9b9b9\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"TEXT\" />",
                    "                                       </cursor>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"132.0\" layoutY=\"36.0\" text=\"Example@gmail.com\" textFill=\"#b2b2b2\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"TEXT\" />",
                    "                                       </cursor>",
                    "                                    </Label>",
                    "                                    <Button layoutX=\"343.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Reveal\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                    <Button layoutX=\"405.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Change\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                    <Button layoutX=\"433.0\" layoutY=\"6.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"🗑\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                 </children>",
                    "                              </Pane>",
                    "                              <Pane layoutX=\"82.0\" layoutY=\"373.0\" prefHeight=\"97.0\" prefWidth=\"472.0\">",
                    "                                 <children>",
                    "                                    <Rectangle arcHeight=\"15.0\" arcWidth=\"15.0\" fill=\"#202225\" height=\"96.0\" opacity=\"0.76\" stroke=\"#979797\" strokeLineCap=\"ROUND\" strokeWidth=\"0.0\" width=\"471.0\" />",
                    "                                    <Label layoutX=\"14.0\" layoutY=\"9.0\" text=\"Instagram\" textFill=\"#b5b5b5\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri Bold\" size=\"20.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"55.0\" layoutY=\"36.0\" text=\"Account:\" textFill=\"#b5b5b5\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"50.0\" layoutY=\"62.0\" text=\"Password:\" textFill=\"#bfbfbf\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"132.0\" layoutY=\"64.0\" text=\"*********\" textFill=\"#b9b9b9\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"TEXT\" />",
                    "                                       </cursor>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"132.0\" layoutY=\"36.0\" text=\"Example@gmail.com\" textFill=\"#b2b2b2\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"TEXT\" />",
                    "                                       </cursor>",
                    "                                    </Label>",
                    "                                    <Button layoutX=\"343.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Reveal\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                    <Button layoutX=\"405.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Change\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                    <Button layoutX=\"433.0\" layoutY=\"6.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"🗑\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                 </children>",
                    "                              </Pane>",
                    "                              <Pane layoutX=\"83.0\" layoutY=\"488.0\" prefHeight=\"97.0\" prefWidth=\"472.0\">",
                    "                                 <children>",
                    "                                    <Rectangle arcHeight=\"15.0\" arcWidth=\"15.0\" fill=\"#202225\" height=\"96.0\" opacity=\"0.76\" stroke=\"#979797\" strokeLineCap=\"ROUND\" strokeWidth=\"0.0\" width=\"471.0\" />",
                    "                                    <Label layoutX=\"14.0\" layoutY=\"9.0\" text=\"LinkedIn\" textFill=\"#b5b5b5\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri Bold\" size=\"20.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"55.0\" layoutY=\"36.0\" text=\"Account:\" textFill=\"#b5b5b5\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"50.0\" layoutY=\"62.0\" text=\"Password:\" textFill=\"#bfbfbf\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"132.0\" layoutY=\"64.0\" text=\"*********\" textFill=\"#b9b9b9\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"TEXT\" />",
                    "                                       </cursor>",
                    "                                    </Label>",
                    "                                    <Label layoutX=\"132.0\" layoutY=\"36.0\" text=\"Example@gmail.com\" textFill=\"#b2b2b2\">",
                    "                                       <font>",
                    "                                          <Font name=\"Calibri\" size=\"18.0\" />",
                    "                                       </font>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"TEXT\" />",
                    "                                       </cursor>",
                    "                                    </Label>",
                    "                                    <Button layoutX=\"343.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Reveal\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                    <Button layoutX=\"405.0\" layoutY=\"60.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"Change\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                    <Button layoutX=\"433.0\" layoutY=\"6.0\" mnemonicParsing=\"false\" style=\"-fx-background-color: grey;\" text=\"🗑\">",
                    "                                       <effect>",
                    "                                          <DropShadow height=\"7.86\" radius=\"3.43\" width=\"7.86\" />",
                    "                                       </effect>",
                    "                                       <cursor>",
                    "                                          <Cursor fx:constant=\"HAND\" />",
                    "                                       </cursor>",
                    "                                    </Button>",
                    "                                 </children>",
                    "                              </Pane>",
                    "                           </children>",
                    "                        </AnchorPane>",
                    "                        <AnchorPane minHeight=\"0.0\" minWidth=\"0.0\" prefHeight=\"180.0\" prefWidth=\"200.0\" />",
                    "                     </items>",
                    "                  </SplitPane>",
                    "                  <HBox.alignment>",
                    "                     <Pos fx:constant=\"CENTER_LEFT\" />",
                    "                  </HBox.alignment>",
                    "               </children>",
                    "            </HBox>",
                    "         </content>",
                    "      </Tab>",
                    "   </tabs>",
                    "   <effect>",
                    "      <DropShadow />",
                    "   </effect>",
                    "   <focusTraversable>true</focusTraversable>",
                    "   <stylesheets>",
                    "      <URL value=\"../stylesheet.css\" />",
                    "   </stylesheets>",
                    "</TabPane>"};
        New.passKeeper = passKeeper;
        New.newPane = newPane;



        New.combineFXML();
        assertArrayEquals(expected, New.newFXML);

    }


}